// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// ExactFunctionalTest
double ExactFunctionalTest(const IntegerMatrix& nm);
RcppExport SEXP FunChisq_ExactFunctionalTest(SEXP nmSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type nm(nmSEXP);
    __result = Rcpp::wrap(ExactFunctionalTest(nm));
    return __result;
END_RCPP
}
