// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// ExactFunctionalTest
double ExactFunctionalTest(const IntegerMatrix& nm);
RcppExport SEXP FunChisq_ExactFunctionalTest(SEXP nmSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type nm(nmSEXP);
    __result = Rcpp::wrap(ExactFunctionalTest(nm));
    return __result;
END_RCPP
}
// interactions
DataFrame interactions(const IntegerMatrix& expression_matrix, const List& parent_index, const IntegerVector& child_index, const String& index_kind);
RcppExport SEXP FunChisq_interactions(SEXP expression_matrixSEXP, SEXP parent_indexSEXP, SEXP child_indexSEXP, SEXP index_kindSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type expression_matrix(expression_matrixSEXP);
    Rcpp::traits::input_parameter< const List& >::type parent_index(parent_indexSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type child_index(child_indexSEXP);
    Rcpp::traits::input_parameter< const String& >::type index_kind(index_kindSEXP);
    __result = Rcpp::wrap(interactions(expression_matrix, parent_index, child_index, index_kind));
    return __result;
END_RCPP
}
